name: Run Auto Sign 

on:
  workflow_dispatch:
  schedule:
    # UTC time
    - cron: "0 0 * * *"

env:
  ZWXQ_USERNAME: ${{ secrets.ZWXQ_USERNAME }}
  ZWXQ_PASSWORD: ${{ secrets.ZWXQ_PASSWORD }}
  AIRBOSHI_TOKEN: ${{ secrets.AIRBOSHI_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        id: build
        run: |
          npm install
      - name: Run 
        id: run
        run: |
          node src/index.js 
